spring:
  application:
    name: msgateway
    
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          
          
server:
  port: 8080
  
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://login:senha@localhost:8761/eureka
